version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: bitroid
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: 
          name: Print release details
          command: ls;pwd;cat /etc/*release; rm -rf *;git clone https://github.com/hemanth22/ansible-role-butler.git hemanth22.butler;ls -la
      - run: 
          name: Pulling molecule docker
          command: docker pull quay.io/ansible/molecule:2.20
      - run: 
          name: Test Ansible playbook code.
          command: docker run --rm -it -v "$(pwd)":/tmp/$(basename "${PWD}"):ro -w /tmp/$(basename "${PWD}") quay.io/ansible/molecule:2.20 molecule test
