---
version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            apk --no-cache add curl
            pip install wget
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76

      - run:
          name: Pulling molecule docker.
          command: docker pull quay.io/ansible/molecule:2.20

      - run:
          name: Test Ansible playbook code.
          command: docker run --rm -it -v "$(pwd)":/tmp/$(basename "${PWD}"):ro -w /tmp/$(basename "${PWD}") quay.io/ansible/molecule:2.20 molecule test
