version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            apk --no-cache add curl
            pip install wget
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76

      - run:
          name: Getout of the code.
          command: cd ../

      - run:
          name: Duplicate the code.
          command: cp -rf ansible-role-butler hemanth22.butler
          
      - run:
          name: Checking to the code.
          command: cd hemanth22.butler

      - run:
          name: Display version of the docker.
          command: cat /etc/*release
          
      - run:
          name: Performing molecule test for ansible role.
          command: docker run --rm -it -v "$(pwd)":/tmp/$(basename "${PWD}"):ro -v /var/run/docker.sock:/var/run/docker.sock -w /tmp/$(basename "${PWD}") quay.io/ansible/molecule:2.20 molecule test

